package com.udemy.springframework.springrt.model;


import java.util.List;

import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

// This class has been created to organize the paged response generated by the listofbeers method

@JsonIgnoreProperties(ignoreUnknown = true, value = "pageable")
public class RestPageImpl<BeerModel> extends PageImpl<BeerModel> {
	
	@JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
	public RestPageImpl(@JsonProperty("content") List<com.udemy.springframework.springrt.model.BeerModel> content,
            @JsonProperty("number") int page,
            @JsonProperty("size") int size,
            @JsonProperty("totalElements") long total) {
super((List<BeerModel>) content, PageRequest.of(page, size), total);
}

public RestPageImpl(List<BeerModel> content, Pageable pageable, long total) {
super(content, pageable, total);
}

public RestPageImpl(List<BeerModel> content) {
super(content);
}

}
